### ISSUE TITLE
Button formatting

### ISSUE THREAD

**Issue by rtp4jc** [ThomasStansel/projectFalcon#7]
I need to be able to format each button according to the type it's supposed to be (add, up, down). Right now, the buttons in base.html have a consistent value and id, but those in search_results.html have a consistent name and value. However, we will need to remove the value soon in order to only show the image and not "Add", "Up", or "Down".  If you could decide whether I should use the name to determine the type of button or the id, that would be great.

**Comment by TStansel** [comment]
For search_results.html I think using name would be best. I am still pretty confused at why the add buttons are not calling the addingSongs method in the projectFalcon.py file so I haven't made really any progress so far.

**Comment by TStansel** [comment]
@RyanPeterson18

**Comment by rtp4jc** [comment]
Ok, I'll wait until we get it unified between base and search_results before I finalize the formatting.

**Comment by TStansel** [comment]
Ok so using name is best because as of now the only way I can distinguish betweens buttons is by using their value variable. I changed the values for the vote buttons and I will merge with master so we are all on the same page. So you can finalize the formatting when you are ready. @RyanPeterson18

**Comment by TStansel** [comment]
OK so there were a bunch of conflicts so I think i fixed it but i also could have deleted a bunch of coded that was needed so review the code and see if there are any changes you need to change back then push them to master then we should be all good again. I won't be able to post on master tomorrow so if you can push them by then great if not no worries just lemme know once you have reviewed it and decided it was how you left it

**Comment by rtp4jc** [comment]
Will do.

**Comment by TStansel** [comment]
Have you had a chance to review the merged code? @RyanPeterson18

**Comment by TStansel** [comment]
Ok so the buttons all work so I shouldn't have to mess with the html code anymore. Also it appears using the id is best for each button

**Comment by TStansel** [comment]
@RyanPeterson18
